### ISSUE TITLE
sensor data

### ISSUE THREAD

**Issue by 1zw** [chenyilan/Y-Net#1]
I would like to ask how to generate the corresponding sensor data. Would you mind providing a copy of the matlab code and the detailed source of the data?

**Comment by gguyinging** [comment]
我想问一下，rawdata是仿真中128个传感器接受的信号，reconstructions是我用传感器接收到的光声信号进行DAS重建得到的图像数据，beamform是我的原始图片，我的理解是这样的，对吗？然后我想问一下我的传感器接收信号大小是（1,1,10001,128），最后 out = x5 + bx5这里面得到的数据是torch.Size([1, 256, 31, 8])
torch.Size([1, 256, 8, 8])我该怎么更改，是我仿真时，传感器接收信号的问题吗？
